mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from todoList import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
    path("__reload__/", include("django_browser_reload.urls")),
]

todoList/urls.py
from django.urls import path
from .views import*

app_name = "todolist"
urlpatterns = [
    path("create", create, name='create'),
    path("", read, name='read'),
    path("delete", delete, name='delete'),
    path("update", update, name='update'),
    path("modify", modify, name='modify'),
    path("achever", achever, name='achever'),
]

todoList/models.py
from django.db import models

# Create your models here.

todoList/views.py
from django.shortcuts import render, get_object_or_404
import pymongo
from .utils import get_db_handle
from django.http import HttpResponse
from bson.objectid import ObjectId
from django.conf import settings
from pprint import pprint

dbname, my_client = get_db_handle('todo_list','localhost',27017)
# Now get/create collection name (remember that you will see the database in your mongodb cluster only after you create a collection
collection_name = dbname["todo_list_task"]

# Create your views here.
def create(request):
    title = request.POST.get('title',"Non défini")
    description = request.POST.get('description',"Non défini")
    etat = False
    #let's create two documents
    task= {
        "title": title,
        "description": description,
        "etat": etat,
    }
    # Insert the documents
    collection_name.insert_one(task)

    todo = collection_name.find()

    todolist = [{'id': str(td["_id"]), 'title' : td["title"], 'description' : td["description"], 'etat' : td["etat"]} for td in todo]

    nbTache = collection_name.count_documents({})
    nbTacheFini = collection_name.count_documents({"etat":True})
    nbTacheEnCours = collection_name.count_documents({"etat":False})
    return render(request, "list/create.html",{"todolist":todolist,
                                               "nbTache":nbTache,
                                               "nbTacheFini":nbTacheFini,
                                               "nbTacheEnCours":nbTacheEnCours,
                                               })
    
    return render(request, "list/create.html")

def read(request):
    todo = collection_name.find()

    todolist = [{'id': str(td["_id"]), 'title' : td["title"], 'description' : td["description"], 'etat' : td["etat"]} for td in todo]

    nbTache = collection_name.count_documents({})
    nbTacheFini = collection_name.count_documents({"etat":True})
    nbTacheEnCours = collection_name.count_documents({"etat":False})
    return render(request, "list/create.html",{"todolist":todolist,
                                               "nbTache":nbTache,
                                               "nbTacheFini":nbTacheFini,
                                               "nbTacheEnCours":nbTacheEnCours,
                                               })

def delete(request):

    choice = request.POST.get('delete').split(',')
    print(choice)
    for c in choice:
        collection_name.delete_one({"_id":ObjectId(c)})

    todo = collection_name.find()

    todolist = [{'id': str(td["_id"]), 'title' : td["title"], 'description' : td["description"], 'etat' : td["etat"]} for td in todo]

    nbTache = collection_name.count_documents({})
    nbTacheFini = collection_name.count_documents({"etat":True})
    nbTacheEnCours = collection_name.count_documents({"etat":False})
    return render(request, "list/create.html",{"todolist":todolist,
                                               "nbTache":nbTache,
                                               "nbTacheFini":nbTacheFini,
                                               "nbTacheEnCours":nbTacheEnCours,
                                               })


def update(request):
    id = ObjectId(request.POST.get('id'))
    task = [{'id': str(td["_id"]), 'title' : td["title"], 'description' : td["description"], 'etat' : td["etat"]} for td in collection_name.find({"_id":id})]
    print(task)
        
    return render(request,"list/modify.html",{"task":task})
    
def modify(request):
    id = ObjectId(request.POST.get('id'))
    title = request.POST.get('title')
    description = request.POST.get('description')
    etat = request.POST.get('etat') == 'true'
    
    collection_name.update_one({"_id": id},{"$set":{"title":title, "description":description, "etat":etat}})
    task = [{'id': str(td["_id"]), 'title' : td["title"], 'description' : td["description"], 'etat' : td["etat"]} for td in collection_name.find({"_id":id})]
    return render(request,"list/modify.html",{"task":task})

def achever(request):
    id = ObjectId(request.POST.get('achever'))

    collection_name.update_one({"_id":id},{"$set":{"etat" : True}})

    todo = collection_name.find()

    todolist = [{'id': str(td["_id"]), 'title' : td["title"], 'description' : td["description"], 'etat' : td["etat"]} for td in todo]

    nbTache = collection_name.count_documents({})
    nbTacheFini = collection_name.count_documents({"etat":True})
    nbTacheEnCours = collection_name.count_documents({"etat":False})
    return render(request, "list/create.html",{"todolist":todolist,
                                               "nbTache":nbTache,
                                               "nbTacheFini":nbTacheFini,
                                               "nbTacheEnCours":nbTacheEnCours,
                                               })

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

todoList/templates/list/create.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
		<style>
			.conteneur{
				height : 550px;
			}
		</style>
		{% load static %}
		<script src="{% static 'jquery.js'%}"></script>
	</head>

	<body class="absolute w-full">
		<div class="flex justify-between">
			<div>
				<label>Nombre de tache</label>
				<div>{{nbTache}}</div>
			</div>
			<div>
				<label>Tache terminer</label>
				<div>{{nbTacheFini}}</div>
			</div>
			<div>
				<label>Tache en cours</label>
				<div>{{nbTacheEnCours}}</div>
			</div>
		</div>
		<div class="w-full flex justify-center">
			<div class="conteneur w-1/2 drop-shadow-md bg-slate-100" >
			{% if todolist %}
				<ul>
				{% for todo in todolist %}
					<div class="flex">
						<div><input type="checkbox" name="chk" value="{{todo.id}}" class="task{{ forloop.counter0 }}"></input></div>
						<div class="w-1/3"><li>{{todo.title}}</li></div>
						<div class="w-1/3"><p>{{todo.description}}</p></div>
						{% if todo.etat %}
						<div class="w-1/3"><p class="text-green-300">Terminer</p></div>
						{% else %}
						<div class="w-1/3"><p class="text-red-600">En cours</p></div>
						{% endif %}
					</div>
				{% endfor %}
				</ul>
			{% endif %}
			</div>
		</div>
		<div class="flex justify-around">
			<button id="create">Ajouter</button>
			<form method="post" action="{% url "todolist:update" %}">
				{% csrf_token %}
				<input type="text" id ="id" class="hidden" name="id" value="{{tk.id}}">
				<button id="update" type="submit" disabled>Modifier</button>
			</form>
			<form method="post" action="{% url "todolist:delete" %}">
				{% csrf_token %}
				<input name = "delete" class="hidden" id="inputDelete">
				<button id="delete" type="submit">Supprimer</button>
			</form>
			<form method="post" action="{% url "todolist:achever" %}">
				{% csrf_token %}
				<input name="achever" class="hidden" id="inputAchever">
				<button id="achever" type="submit" disabled>Achever</button>
			</form>
		</div>

		<div class="flex justify-center">
			<div id = "ajouterModal" class="w-96 h-64 bg-slate-50 absolute top-20 drop-shadow-md p-8 hidden">
				<button class="absolute top-0 right-1" id="cancelCreate">X</button>
				<form class="w-full h-full" method="POST" action="{% url "todolist:create" %}">
					{% csrf_token %}
					<div>
						<label>Title</label>
						<input type="text" name ="title">
					</div>
					<div class="flex flex-col h-1/2">
						<label>Description</label>
						<input type="textarea" class="h-full" name="description">
					</div>
					<button type="submit">Inserer</button>
				</form>
			</div>
		</div>

	</body>
	<script src="{% static 'todoList/js/delete.js'%}"></script>
	<script src="{% static 'todoList/js/create.js'%}"></script>
	<script src="{% static 'todoList/js/update.js'%}"></script>
</html>

todoList/templates/list/modify.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Update</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
		<style>
			.conteneur{
				height : 550px;
			}
		</style>
		{% load static %}
		<script src="{% static 'jquery.js'%}"></script>
	</head>

	<body>
        {% for tk in task %}
        <form class="w-full h-full" method="POST" action="{% url "todolist:modify" %}">
            {% csrf_token %}

            <div>
                <label>Title</label>
                <input type="text" name ="id" value="{{tk.id}}" class="hidden">
                <input type="text" name ="title" value="{{tk.title}}">
            </div>
            <div class="flex flex-col h-1/2">
                <label>Description</label>
                <input type="textarea" class="h-full" name="description" value="{{tk.description}}">
            </div>
            <div>
                <label>Etat</label><br>
                <input type="radio" value = "false" id = "encours" 
                {% if not tK.etat %} checked = "checked" {% endif %} name="etat">
                <label for="encours" >En cours</label><br>
                <input type="radio" value = "true" id = "terminer"
                {% if tk.etat %} checked="checked" {% endif %} name="etat">
                <label for="terminer" >Terminer</label><br>
            </div>
            <button type="submit">Modifier</button>
        </form>
        {% endfor %}
	</body>
</html>